name: Build Android APK

on:
  push:
    branches: [ main ] # main branch ထဲကို ကုဒ် push လုပ်တိုင်း အလုပ်လုပ်မည်

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-cache: 'pip'

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev
        pip install --user --upgrade buildozer cython

    - name: Build with Buildozer
      run: |
        buildozer android debug
      env:
        ACCEPT_SDK_LICENSE: "y"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: UBT-Shop-APK
        path: bin/*.apk
