      - name: Sign Android APK with Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > release.jks
          BUILD_TOOLS_PATH=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          ORIGINAL_APK=$(find android/app/build/outputs/apk/release/ -name "*.apk" | head -n 1)
          
          # Zipalign လုပ်ပြီး နာမည်ပေးခြင်း
          $BUILD_TOOLS_PATH/zipalign -v 4 "$ORIGINAL_APK" my-signed-app.apk
          
          # V1, V2, V3 Signing အကုန်လုံးထည့်ပြီး လက်မှတ်ထိုးခြင်း
          # ဒါမှသာ Google Play Protect က Scan ဖတ်ခွင့်ပေးမှာပါ
          $BUILD_TOOLS_PATH/apksigner sign --ks release.jks \
            --ks-pass pass:"$KEYSTORE_PASSWORD" \
            --ks-key-alias "$KEY_ALIAS" \
            --v1-signing-enabled true \
            --v2-signing-enabled true \
            --v3-signing-enabled true \
            my-signed-app.apk
